### ISSUE TITLE
No commands work in Matrix

### ISSUE THREAD

**Issue by lmarianski** [matrix-discord/mx-puppet-discord#101]
I'm able to add the bot in the "people" tab on Element, but it never responds
Log:
```
Sep-30 21:27:10.327 [Store] info: Starting DB Init
Sep-30 21:27:10.329 [Store] info: Filename present in config, using sqlite
Sep-30 21:27:10.329 [SQLite3] info: Opening database.db
Sep-30 21:27:10.331 [Store] info: Database schema version is 16, latest version is 16
Sep-30 21:27:10.333 [Store] info: Starting DB Init
Sep-30 21:27:10.334 [Store] info: Database schema version is 4, latest version is 4
Sep-30 21:27:10.334 [PuppetBridge] info: Starting application service....
Sep-30 21:27:10.337 [bot-sdk-MatrixLiteClient] info: (REQ-1) POST http://matrix:8008/_matrix/client/r0/register
Sep-30 21:27:10.355 [PuppetBridge] info: Application service started!
Sep-30 21:27:10.355 [PuppetBridge] info: Setting bridge user data...
Sep-30 21:27:10.356 [bot-sdk-MatrixLiteClient] info: (REQ-2) GET http://matrix:8008/_matrix/client/r0/profile/%40_discordpuppet_bot%3Am00nlit.duckdns.org
Sep-30 21:27:10.362 [PuppetBridge] info: Activating users...
Sep-30 21:27:10.363 [PresenceHandler] info: Starting presence handler with new interval 500ms
```
the only part of the config that I changed:
```yml
bridge:
  # Port to host the bridge on
  # Used for communication between the homeserver and the bridge
  port: 8434

  # The host connections to the bridge's webserver are allowed from
  bindAddress: 0.0.0.0

  # Public domain of the homeserver
  domain: m00nlit.duckdns.org

  # Reachable URL of the Matrix homeserver
  homeserverUrl: http://matrix:8008
```
registration yaml
the file is under `/data/appservices/discord-registration.yaml` on the synapse container
```yml
as_token: 863108ea-bca4-4aff-ae68-57b38ebed436
hs_token: e04a45bf-b67b-46c5-b229-7a7115a4233a
id: discord-puppet
namespaces:
  users:
    - exclusive: true
      regex: '@_discordpuppet_.*'
  rooms: []
  aliases:
    - exclusive: true
      regex: '#_discordpuppet_.*'
protocols: []
rate_limited: false
sender_localpart: _discordpuppet_bot
url: 'http://mx-puppet-discord:8434'
```
Both are running under docker (`matrix` is the synapse server)
