### ISSUE TITLE
Docker doku

### ISSUE THREAD

**Issue by wuast94** [matrix-discord/mx-puppet-discord#125]
Can you explain more how the container should be mounted? ports, path, etc
or at leas a docker-compose.yml were anyone can get this infos :)

**Comment by Jarzebowsky** [comment]
```
version: "3.3"

services:
    mx-puppet-discord:
        image: sorunome/mx-puppet-discord
        restart: unless-stopped
        ports:
            - '8384:8384'
        volumes:
            - .:/data
        networks: ["server"]
    mx-puppet-discord-db:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
            POSTGRES_DB: database
            POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
        volumes:
            - "postgresdata:/var/lib/postgresql/"
        networks: ["server"]
volumes:
    postgresdata:

networks:
    server:
        external: true
```

That's mine **docker-compose.yml** file. Remember to have the matrix server in the same network.
You need to configure also in **config.yaml** file those lines:
```
# The host connections to the bridge's webserver are allowed from
  bindAddress: 0.0.0.0

database:
  # Use Postgres as a database backend. If set, will be used instead of SQLite3
  #
  # Connection string to connect to the Postgres instance
  # with username "user", password "pass", host "localhost" and database name "dbname".
  #
  # Modify each value as necessary
  connString: "postgres://user:password@mx-puppet-discord-db/database?sslmode=disable"

  # Use SQLite3 as a database backend
  #
  # The name of the database file
  #filename: 'data/database.db'
```

And also you are in need to change generated **discord-registration.yaml** file:
```
url: 'http://mx-puppet-discord:8384'
```
