### ISSUE TITLE
Receiving thousand transactions per second

### ISSUE THREAD

**Issue by coderPaddyS** [matrix-discord/mx-puppet-discord#137]
Hey guys!
I just tried to set up the bridge as described in README.md and encountered a problem, which I am not able to solve on my own.
After running `npm run start` to start the bot, the output is as follows and I assume everything is fine:
```
Apr-4 22:45:23.181 [Store] info: Starting DB Init
Apr-4 22:45:23.186 [Store] info: connString present in config, using postgres
Apr-4 22:45:23.186 [Postgres] info: Opening @localhost/mx-puppet-discord?sslmode=disable
Apr-4 22:45:23.244 [Store] info: Database schema version is 16, latest version is 16
Apr-4 22:45:23.249 [Store] info: Starting DB Init
Apr-4 22:45:23.253 [Store] info: Database schema version is 4, latest version is 4
Apr-4 22:45:23.254 [PuppetBridge] info: Starting application service....
Apr-4 22:45:23.261 [bot-sdk-MatrixLiteClient] info: (REQ-1) POST https://matrix.example.com/_matrix/client/r0/register
Apr-4 22:45:23.325 [PuppetBridge] info: Application service started!
Apr-4 22:45:23.326 [PuppetBridge] info: Setting bridge user data...
Apr-4 22:45:23.327 [bot-sdk-MatrixLiteClient] info: (REQ-2) GET https://matrix.example.com/_matrix/client/r0/profile/%40_discordpuppet_bot%3Aexample.de
Apr-4 22:45:23.348 [PuppetBridge] info: Activating users...
Apr-4 22:45:23.355 [PresenceHandler] info: Starting presence handler with new interval 2000ms
```

If I then try to invite the bot to join my room, something weird happens, as described in the title:
```
127.0.0.1 - - [04/Apr/2021:20:25:16 +0000] "PUT /transactions/19355?access_token=[redacted] HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Apr-4 22:25:16.098 [bot-sdk-Appservice] info: Processing transaction 19356
127.0.0.1 - - [04/Apr/2021:20:25:16 +0000] "PUT /transactions/19356?access_token=[redacted] HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Apr-4 22:25:16.105 [bot-sdk-Appservice] info: Processing transaction 19357
127.0.0.1 - - [04/Apr/2021:20:25:16 +0000] "PUT /transactions/19357?access_token=[redacted] HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Apr-4 22:25:16.109 [bot-sdk-Appservice] info: Processing transaction 19358
127.0.0.1 - - [04/Apr/2021:20:25:16 +0000] "PUT /transactions/19358?access_token=[redacted] HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
...
```
As described and as you can see by the time stamp, there are way too many transactions per second. The bot also does join as expected nor does anything else happens.

I've changed some regexes and naming schemas and set the domain and homeserverUrl fields accordingly to my server.
The resulting discord-registration.yaml is as follows:
```
as_token: [redacted]
hs_token: [redacted]
id: discord-puppet
namespaces:
  users:
    - exclusive: true
      regex: '@_discordpuppet_.*'
  rooms: []
  aliases:
    - exclusive: true
      regex: '#_discordpuppet_.*'
protocols: []
rate_limited: false
sender_localpart: _discordpuppet_bot
url: 'http://localhost:8434'
de.sorunome.msc2409.push_ephemeral: true
```

My homeserver.log just contains lines like
```
2021-04-04 22:25:16,301 - synapse.http.client - 444 - INFO - as-recoverer-discord-puppet-11 - Received response to PUT http://localhost:8434/transactions/19386?access_token=<redacted>: 200
2021-04-04 22:25:16,305 - synapse.appservice.scheduler - 296 - INFO - as-recoverer-discord-puppet-11 - Retrying transaction 19387 for AS ID discord-puppet
```
for every transaction triggered.

I hope you can solve this problem of mine (and perhaps explain what I did wrong :) )
