### ISSUE TITLE
Puppet Bridge not online on Matrix

### ISSUE THREAD

**Issue by juligreen** [matrix-discord/mx-puppet-discord#53]
After following the steps in the readme I get the following log:

```
Feb-13 01:37:10.588 [Store] info: Starting DB Init
Feb-13 01:37:10.591 [Store] info: Filename present in config, using sqlite
Feb-13 01:37:10.591 [SQLite3] info: Opening database.db
Feb-13 01:37:10.594 [Store] info: Database schema version is 9, latest version is 9
Feb-13 01:37:10.595 [Store] info: Starting DB Init
Feb-13 01:37:10.596 [Store] info: Database schema version is 3, latest version is 3
Feb-13 01:37:10.597 [PuppetBridge] info: Starting application service....
Feb-13 01:37:10.607 [bot-sdk-MatrixLiteClient] info: (REQ-1) POST https://matrix.homeserver.xyz/_matrix/client/r0/register
Feb-13 01:37:10.691 [bot-sdk-MatrixLiteClient] error: (REQ-1) { errcode: 'M_USER_IN_USE', error: 'User ID already taken.' }
Feb-13 01:37:10.693 [PuppetBridge] info: Application service started!
Feb-13 01:37:10.693 [PuppetBridge] info: Setting bridge user data...
Feb-13 01:37:10.694 [bot-sdk-MatrixLiteClient] info: (REQ-2) GET https://matrix.homeserver.xyz/_matrix/client/r0/account/whoami
Feb-13 01:37:10.725 [bot-sdk-MatrixLiteClient] info: (REQ-3) PUT https://matrix.homeserver.xyz/_matrix/client/r0/profile/%40_discordpuppet_bot%3Ahomeserver.xyz/displayname
Feb-13 01:37:10.741 [PuppetBridge] info: Activating users...
Feb-13 01:37:10.742 [PresenceHandler] info: Starting presence handler with new interval 500ms
```

When I invite the bot to a chat in my matrix client the name of the puppet bridge resolves properly, but it never comes online.

Im wondering if I'm doing something really stupid that stops this from working

I also have [mautrix-whatsapp](https://github.com/tulir/mautrix-whatsapp) installed, could this be an issue like the error "M_USER_IN_USE" implies?

My config.yaml:
```
bridge:
  # Port to host the bridge on
  # Used for communication between the homeserver and the bridge
  port: 8434
  # The host connections to the bridge's webserver are allowed from
  bindAddress: localhost
  # Public domain of the homeserver
  domain: homeserver.xyz
  # Reachable URL of the Matrix homeserver
  homeserverUrl: https://matrix.homeserver.xyz

presence:
  # Bridge Discord online/offline status
  enabled: true
  # How often to send status to the homeserver in milliseconds
  interval: 500

provisioning:
  # Regex of Matrix IDs allowed to use the puppet bridge
  whitelist:
    # Allow a specific user
    #- "@user:server\\.com"
    # Allow users on a specific homeserver
    - "@.*:homeserver\\.xyz"
    # Allow anyone
    #- ".*"
  # Regex of Matrix IDs forbidden from using the puppet bridge
  #blacklist:
    # Disallow a specific user
    #- "@user:server\\.com"
    # Disallow users on a specific homeserver
    #- "@.*:yourserver\\.com"

database:
  # Use Postgres as a database backend
  # If set, will be used instead of SQLite3
  # Connection string to connect to the Postgres instance
  # with username "user", password "pass", host "localhost" and database name "dbname".
  # Modify each value as necessary
  #connString: "postgres://user:pass@localhost/dbname?sslmode=disable"
  # Use SQLite3 as a database backend
  # The name of the database file
  filename: database.db

logging:
  # Log level of console output
  # Allowed values starting with most verbose:
  # silly, verbose, info, warn, error
  console: info
  # Date and time formatting
  lineDateFormat: MMM-D HH:mm:ss.SSS
  # Logging files
  # Log files are rotated daily by default
  files:
    # Log file path
    - file: "bridge.log"
      # Log level for this file
      # Allowed values starting with most verbose:
      # silly, debug, verbose, info, warn, error
      level: info
      # Date and time formatting
      datePattern: YYYY-MM-DD
      # Maximum number of logs to keep.
      # This can be a number of files or number of days.
      # If using days, add 'd' as a suffix
      maxFiles: 14d
      # Maximum size of the file after which it will rotate. This can be a
      # number of bytes, or units of kb, mb, and gb. If using the units, add
      # 'k', 'm', or 'g' as the suffix
      maxSize: 50m

```
